export const data=[
    {
        id:1,
        name:"Vijay Kumar",
        Image:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.industrialempathy.com%2Fposts%2Fimage-optimizations%2F&psig=AOvVaw0rcOz2aWeY5nxQ164trjcw&ust=1664427294356000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKjNxoPZtvoCFQAAAAAdAAAAABAE",
        age:45,
        location:"Mumbai",
    },
    {
        id:2,
        name:"Rahul Kumar",
        Image:"https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.eso.org%2Fimages%2Fpublicationjpg%2Feso1907a.jpg&imgrefurl=https%3A%2F%2Fwww.eso.org%2Fpublic%2Fimages%2Feso1907a%2F&tbnid=0RNGd-U_ZZMWyM&vet=12ahUKEwjArJjP06z6AhWHk9gFHWEJA8UQMygRegUIARCxAQ..i&docid=fjQERhW14-2NKM&w=4000&h=2330&q=image%20&ved=2ahUKEwjArJjP06z6AhWHk9gFHWEJA8UQMygRegUIARCxAQ",
        age:40,
        location:"Bangalore",
    },
    {
        id:3,
        name:"Sham Kumar",
        Image:"https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
        age:43,
        location:"Chennai",
    },
    {
        id:4,
        name:"Suraya Kumar",
        Image :"https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.industrialempathy.com%2Fimg%2Fremote%2FZiClJf-1920w.jpg&imgrefurl=https%3A%2F%2Fwww.industrialempathy.com%2Fposts%2Fimage-optimizations%2F&tbnid=z4_uU0QB2pe-SM&vet=12ahUKEwjArJjP06z6AhWHk9gFHWEJA8UQMygQegUIARCvAQ..i&docid=7SySw5zvOgPYAM&w=1920&h=1080&q=image%20&ved=2ahUKEwjArJjP06z6AhWHk9gFHWEJA8UQMygQegUIARCvAQ",
        age:42,
        location:"Delhi",
    },
    {
        id:5,
        name:"Dinesh",
        Image :"https://www.google.com/imgres?imgurl=https%3A%2F%2Fimages.pexels.com%2Fphotos%2F33044%2Fsunflower-sun-summer-yellow.jpg%3Fcs%3Dsrgb%26dl%3Dpexels-pixabay-33044.jpg%26fm%3Djpg&imgrefurl=https%3A%2F%2Fwww.pexels.com%2Fsearch%2Fsun%2F&tbnid=ThwRLf7Ik44zdM&vet=12ahUKEwjArJjP06z6AhWHk9gFHWEJA8UQMygSegUIARCzAQ..i&docid=_fD5XoaNdUP2YM&w=4752&h=3168&q=image%20&ved=2ahUKEwjArJjP06z6AhWHk9gFHWEJA8UQMygSegUIARCzAQ",
        age:39,
        location:"Hydrabad",
    },
    {
        id:6,
        name:"Ramesh",
        Image :"https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.vecteezy.com%2Fpacks%2Fmedia%2Fvectors%2Fterm-bg-1-666de2d9.jpg&imgrefurl=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos&tbnid=QOZymhPf48LDYM&vet=12ahUKEwjArJjP06z6AhWHk9gFHWEJA8UQMygbegUIARDHAQ..i&docid=ibTdn4unYxO9nM&w=550&h=549&q=image%20&ved=2ahUKEwjArJjP06z6AhWHk9gFHWEJA8UQMygbegUIARDHAQ",
        age:38,
        location:"Noida",
    },
    {
        id:7,
        name:"Nadir",
        Image :"https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fnature%2F&psig=AOvVaw0yhFqe5ekUImAUgBD1_6Sq&ust=1664082255902000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCNjvttPTrPoCFQAAAAAdAAAAABAN",
        age:37,
        location:"Nagpur",
    },
    {
        id:8,
        name:"Shams",
        Image :"https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fimages%2Fnature&psig=AOvVaw0yhFqe5ekUImAUgBD1_6Sq&ust=1664082255902000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCNjvttPTrPoCFQAAAAAdAAAAABAS",
        age:36,
        location:"Jhansi",
    },
    {
        id:9,
        name:"Wasim",
        Image :"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.jpegmini.com%2F&psig=AOvVaw0yhFqe5ekUImAUgBD1_6Sq&ust=1664082255902000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCNjvttPTrPoCFQAAAAAdAAAAABAX",
        age:35,
        location:"Punjab",
    },
    {
        id:10,
        name:"Tarique",
        Image :"https://www.google.com/imgres?imgurl=https%3A%2F%2Fhtml5box.com%2Fhtml5gallery%2Fimages%2FSwan_1024.jpg&imgrefurl=https%3A%2F%2Fhtml5box.com%2Fhtml5gallery%2Fdemo_fullscreen.php&tbnid=cMDWvPzZurThEM&vet=10CAUQxiAoBGoXChMI2O-209Os-gIVAAAAAB0AAAAAEBo..i&docid=ULjf1h7EfR_ttM&w=1024&h=768&itg=1&q=image%20&ved=0CAUQxiAoBGoXChMI2O-209Os-gIVAAAAAB0AAAAAEBo",
        age:34,
        location:"Kerala",
    },
    {
        id:11,
        name:"Salim",
        Image :"https://www.google.com/imgres?imgurl=https%3A%2F%2Fhtml5box.com%2Fhtml5gallery%2Fimages%2FSwan_1024.jpg&imgrefurl=https%3A%2F%2Fhtml5box.com%2Fhtml5gallery%2Fdemo_fullscreen.php&tbnid=cMDWvPzZurThEM&vet=10CAUQxiAoBGoXChMI2O-209Os-gIVAAAAAB0AAAAAEBo..i&docid=ULjf1h7EfR_ttM&w=1024&h=768&itg=1&q=image%20&ved=0CAUQxiAoBGoXChMI2O-209Os-gIVAAAAAB0AAAAAEBo",
        age:36,
        location:"JHarkhand",
    },
    
]